name: Jest Code Coverage Report
run-name: ${{ github.actor }} is initializing a Code Coverage Report!
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run coverage