---
  ## Super Linter GitHub Actions ##
  name: Javascript Linter
  run-name: ${{ github.actor }} is using the Javascript Linter! 🚀

  on:
    push:
      branches: [ main ]

    pull_request:
      branches: [ main ]


  # Set the Job #
  jobs:
    build:
      # Name the Job
      name: Lint Code Base
      runs-on: ubuntu-latest

      # Grant status permission for MULTI_STATUS #
      permissions:
        contents: read
        packages: read
        statuses: write

      # Load all steps #
      steps:
        # Checkout the code base #
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            # Full git history is needed to get a proper
            # list of changed files within `super-linter`
            fetch-depth: 0

        # Run Linter against code base #
        - name: Lint Code Base
          uses: super-linter/super-linter/slim@v5
          env:
            VALIDATE_ALL_CODEBASE: true
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VALIDATE_JAVASCRIPT_STANDARD: true
            JAVASCRIPT_DEFAULT_STYLE: 'standard'