name: Javascript Testing Suite
run-name: ${{ github.actor }} is running Javascript tests!
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm ci
      - run: cd tests
      - run: npm run test